version: '3'
services:

  app:
    build: .
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
    - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo

volumes:
  node_modules: